server:
  port: 1111
  servlet:
    # 配置访问路径，如果配置该选项，则访问后端系统是需要加下配置的路径
    context-path: /XUpdateService

spring:
  datasource:
    name: XUpdateService
    # 产品线上环境配置
#    url: jdbc:mysql://172.16.105.141:3306/xupdate?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    username: root
#    password: U@RdLB!H4FnxWIs#
    # 杭州线上环境配置
#    url: jdbc:mysql://172.16.105.174:3306/xupdate?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
#    username: root
#    password: Insimga_20230223
    # 杭州测试环境配置
    url: jdbc:mysql://172.16.105.203:3306/xupdate?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: Insigma_20230323
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      # 如果上传的APK包比较大，需要调大上传文件大小上限和请求体大小上限
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.xuexiang.xupdateservice.model

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 上传APK 包保存地址
upload:
  #  file-directory: ./uploads
  file-directory: /home/app/AndroidApk
  keep-name: true

# APK 包下载URL接口地址
download:
  # 开发环境地址
  #  domain: http://10.0.27.16/XUpdateService/update/apk/
  # 线上地址
  domain: https://indigital.insigma.com.cn/XUpdateService/update/apk/